### ISSUE TITLE
Chapter 2 Plot error

### ISSUE THREAD

**Issue by shayegh** [PacktPublishing/Python-for-Finance-Cookbook#3]
Hi,
in chapter two, I follow your code but when I try to use "Plot"
```
# plot results
cerebro.plot(iplot=True, volume=False)
```
 I got following error

```
ReferenceError: IPython is not defined
    at eval (eval at runCodeHere (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:11583), <anonymous>:764:1)
    at runCodeHere (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:11583)
    at t.value (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12015)
    at Di (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:1299316)
    at Li (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:1302238)
    at vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:1315318
    at Object.t.unstable_runWithPriority (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:6091)
    at Sl (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:1315252)
    at Cl (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:1315028)
    at wl (vscode-resource://file///c%3A/Users/mojTaba/.vscode/extensions/ms-python.python-2020.3.69010/out/datascience-ui/notebook/commons.initial.bundle.js:2:1314373)
```

All other parts work as expected.

**Comment by erykml** [comment]
Hi, 

Are you running the code from withing VS Code? This might somehow be an issue. 
Please try running it in Jupyter Notebook/Lab and let me know if the problem persists.

**Comment by shayegh** [comment]
Hi,
Thanks.
You were right. I ran it in vs code and got the error.
when I run it in Jupyter Notebook it works fine.
